### ISSUE TITLE
Register lifeCycle 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/registry-core#2]
Keep Experimental and Stable status even if we add our own entries.
They don't re-appear if recreated manually in the lifeCycle register

-> dev :  looks like a code change

**Comment by afeliachi** [comment]
Details:
The registry provides the possibility to alter the predefined lifeCycle by adding  a **/system/lifecycle** register. As explained in the [wiki](https://github.com/UKGovLD/registry-core/wiki/Life-cycle-customization#customizing-the-life-cycle) this would cause the suppression of the **experimental** and **stable** status. This last behavior is in unsuitable for us because the existing registers (or their content) that are already have **experimental** and **stable** status would lose their status to a **reg:statusNotAccepted** one.
Even if the **experimental** and **stable** status are added manually (with the proper description) or loaded in the same time with the customized lifeCycle register, they would still be suppressed for the already existing registers.
We would like to keep **experimental** and **stable** as core status for the registry if they are already used by existing registers.
