### ISSUE TITLE
Notification level 2 : 'external' involving Kafka or other standard protocol

### ISSUE THREAD

**Issue by sgrellet** [BRGM/registry-core#23]
Allow a user (machine, human) to subscribe to a notification system (a Kafka topic for example)  and receive the corresponding notifications.
a notification stream (Kafka topic for exmaple):
- by register 
- at a whole registry

There is no JENA plugin yet for Change Data Capture as opposed to what we have for relational DB.
But there is an existing process notification sytem in ldregistry loggin each request. This would be a good starting point. 
Building on process notification, it should be straightforward to have a Kafka module

Note
- Epimorphics is working on the Kafka topic on his side
- BRGM is investing on a Kafka based notification system for its information flows

**Comment by der** [comment]
Some clarifying questions:

1. Do the generated messages need to contain the complete payload for the change so that, in principle, a subscriber could maintain a replica of the registry (or a register) just using the notification service? Or is the notification intended to convey that there has been a change to a given register but the client could use a separate mechanism to obtain the full payload needed to replicate the change?

2. When you say "such as a kafka topic" is the requirement to actually implement a kafka producer or is the question of broker protocol support still open?

To explain these two:

A core problem with using kafka for change notification is that it has a quite limited payload size. By default the maximum size of a payload (or a batch of message bodies) is 1Mb. While a broker configuration can be changed to increase this there is always (as far as I know) a hard limit and normally a small one. This can be worked around by splitting big payloads into separate kafka messages (which means you are then creating a new protocol over the top of kafka) or by spilling large kafka payloads out to separate distributed storage (we tend to use AWS S3 for that, but that then becomes a more complex deployment and quite technology specific).

One alternative might be to use something like Apache ActiveMQ to generate AMQP (or STOMP or whatever) protocol messages. That's more platform agnostic but if you actually want to use kafka that would mean running an AMQP (or whatever) broker as well and then have external components forward message from that to kafka, which again would complicate deployment and ops.

3. Would it be acceptable to implement the adaptor as a separate component so that `registry-core` can still be deployed without pulling in a full kafka dependency stack, but if you need this new capability you would deploy a different customised war file?

This is just an option to consider. Technically we could certainly add a kafka or amqp interface directly to `registry-core` but at the cost of increasing the size of the deployed artefact. Having the ability to create extensions like this without having an impact on users who don't need the feature might be helpful. However, to make this possible it would mean splitting registry core into separate lib (`jar` packaged) and `war` artefacts, which would itself have some impact on other users.

4. Can the configuration be static (e.g. via entries in `app.conf` or a configuration file loaded from `app.conf`) or does it have to be dynamic?

**Comment by sgrellet** [comment]
1. “Do the generated messages need to contain the complete payload for the change” 
On that specific point, there may be a debate
First guts feeling would be to say 'No. The idea is be able to subscribe to a given ‘topic’ (using Kafka semantics) and receive notification about RegisterItem (Create, Update, Delete). And if clients want to know more, they would dereference the corresponding URI
But architects tend to say that, doing so, client system, when receiving the update, will all dereference the URI, thus creating an important load on the system. 
The idea would be, for each tiny tiny change, to push it in the correponding topic (on a reg:RegisterItem level)
Thus, the payload would be for each event on reg:RegisterItem.
Then for the initial creation of the topic, on a reg:register there would be as many message as event on reg:RegisterItem

2. No, a strong dependency to Kafka is not required. We are now also testing other approaches like Pulsar. The idea is really to be able to ‘plug’ registry-core to a Pub/Sub messaging system. The question about broker protocol is still open (AMQP or STOMP seem good options)

3. Reply to 2, may help reply to this one (no dependency stack to Kafka but, yes, maybe to AMQP/STOMP). Ideally, just updating registry-core (and then activating it or no via conf) would be great. We don't want a specific 'BRGM customized war'. Plan B, if the dependency stack to either AMQP or STOMP is considered too big, would be a 'plugin' approach.

4. External configuration in file should be good, in term of port, and queue name, protocol version.
No need to have it dynamic

**Comment by der** [comment]
Thanks @sgrellet that helps alot with understanding the requirement.

It does mean it'll be a more complex implementation than we'd hoped. The current replication mechanism allows us to both log and forward all update requests but those are at the API (i.e. the whole transaction level) not at individual register items. 

Splitting those into item level messages of some sort is technically possible, though challenging and will take some thought to figure out a good way to do that.

You mention CRUD style notifications. Is that separation a critical feature? A single edit operation can both add new registrations and update existing register items. If the notifications didn't distinguish between a Create and an Update, might that be acceptable at least initially?

**Comment by der** [comment]
@sgrellet On review I think the internal notification system we have will allow us to do item level notifications so my comments on that part being "challenging" are wrong. The machinery will need some testing and clean up but the foundations are there. 

It would still be useful to know whether a create-or-update message would be acceptable in place of separate create/update but that maybe a lower level detail.

**Comment by afeliachi** [comment]
Thanks Dave
I think It's necessary from the user point of view to distinguish between the create/ update operations though. I think that generally (or at least from the use cases we are dealing with) these two operations would trigger different behaviours from the users.

**Comment by der** [comment]
@afeliachi OK, understood.

One further clarification on configuration. When asking about dynamic configuration I was particularly meaning "how do you imagine choosing which registers to monitor". @sgrellet 's answer could be read as just about the connection to the message bus whereas I'm more concerned with figuring out which registers the notification checks are applied to. 

My default would be to have a configuration file or entry in `app.conf` which lists one or more root registers to be monitored (which can be the whole registry root). All registers under those roots would generate notification messages, including new ones created under one of those roots. Would that be a suitable approach?

Alternative would be to have a system register which lists all such root monitored registers.

**Comment by afeliachi** [comment]
@der  Ok thanks for the clarification.
Both solutions are fine, but I have a preference for the latter. This way it would be easier for all the register managers to config this.
