### ISSUE TITLE
Coherence / matching Tests 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/registry-core#4]
Hinting mechanism generating warnings if a prefLabel, description etc... is already being used
- in the same register
- throughout the registry
  
Triggered
- when editing an item
- when doing bulk upload ?

Questions : 
capacity to upload to upload new 'test suite' VS hardcoded set of tests run everytime

Dev : needed both for back-end and GUI (hinting)

**Comment by sgrellet** [comment]
Hinting like the 'related issue' mechanism currently in Beta in GitHub

**Comment by der** [comment]
This would need to be configurable at least at a registry level and probably at a per-register level.

There is currently an option to configure a per-register SPARQL query to validate a payload but (a) this only returns true/false results and (b) only queries the payload. To implement this hinting you would need a validation query which ran against the entire triple store. That might be possible through an analogous mechanism, though the configured query would have to return some pre-agreed set of bindings which give sufficient information of the UI to provide such hints. Alternative would be a separate mechanism dedicated to just this sort of validation, perhaps as an extension to the existing search functionality. 

The details of exactly when to trigger the checks and how to present the hints will require design work.

**Comment by afeliachi** [comment]
Thanks Dave.  Indeed we figured out the validation of he upload using  **reg:validationQuery** only queries the payload.
We are thinking about a separate  hinting mechanism that allows checking a new bulk or a new manually added entity against the content of the registry.

If it could be helpful. Here are some examples how we do imagine it:
- An additional button to check a new element against the registry content:
![entity_ add_check](https://user-images.githubusercontent.com/17085461/52118301-42997500-2616-11e9-8329-8f7b4f8b2a60.JPG)

That would trigger some warnings about it, by checking the existence or resemblance of its label: 

![entity_ add_check_warning](https://user-images.githubusercontent.com/17085461/52118368-6a88d880-2616-11e9-80e3-b0e5ddfd1605.JPG)


- A new menu element for bulk checking:
![chekc_bulk_example2](https://user-images.githubusercontent.com/17085461/52118175-f0f0ea80-2615-11e9-8d3a-92a2fbe5fb97.jpg)

That shows a dialog  for loading the file and choosing the properties to select the values to check for existence or resemblance, and triggers warnings for its content.

![upload_for_check](https://user-images.githubusercontent.com/17085461/52118449-a02dc180-2616-11e9-8321-1e94ba107a73.JPG)

- A similar checking could be also imagined concerning the label of a new register. The hinting system can be used to warn the user of the existence of another register with the same label.

I hope this gives a preview of the wanted mechanism. What do you think about its implementability  ?

**Comment by der** [comment]
The validation of a single entry should be reasonably straight forward. It would use the search API. In principle that can expose the full Lucene query language which would allow using of Levenshtein distance metric for your "similar to" requirement. Might even be possible to implement just using UI templates.

The bulk checking is harder for several of reasons. First, it means uploading a payload but not processing it, just doing a bulk check. So that would need to be a new API and thus a non-trivial extension to the core. Not a huge amount of work but would further complicate the API with something that could feel niche if it were just checking for similar labels. I think that would need to be treated as a general purpose "validate but don't try to register" API and associated UI . The validation would initially be the same as the existing validation except for the additional of the matching/similar labels report. In principle it would given a hook for future "lint" style validation of proposed payloads. 

One tricky part is the requirement in the bulk upload to allow arbitrary properties to be checked for similarity. If that's really needed then it's implementable (though similarity should only be defined on string-valued properties I think). However, if that could be relaxed to just be any of the label properties used for the text indexing then would simplify things a little since the actual checks could use the text search.

**Comment by afeliachi** [comment]
Ok great.

When I started to read you last paragraph I thought the same thing: Why not use the same label properties we specify in the conf for indexing. I was not disappointed when I finished the paragraph :smile:. 
Seems good to me since it makes things even easier for our end-users.

Can we consider that you validate this request then?

**Comment by afeliachi** [comment]
> Can we consider that you validate this request then?

I meant do you think that the details we provided are enough for the estimating the required work.
thanks

**Comment by der** [comment]
Yes thanks. Given the clarification on limiting to the text indexed properties that's enough to estimate from.
